### ISSUE TITLE
does not scale well to large datasets

### ISSUE THREAD

**Issue by jelmerk** [Microsoft/HNSW.Net#6]
Trying to create an index with a mere 100.000 elements seems to cause an OutOffMemoryException 

```csharp
       /// <summary>
        /// See if we can create a large graph
        /// </summary>
        [TestMethod]
        public void LargeGraphTest()
        {
            var parameters = new SmallWorld<float[], float>.Parameters();
            parameters.M = 15;
            parameters.LevelLambda = 1 / Math.Log(parameters.M);

            var graph = new SmallWorld<float[], float>(CosineDistance.NonOptimized);

            var myRandom = new Random(42);

            var manyVectors = new List<float[]>();
            for (int i = 0; i < 100_000; i++)
            {
                var randomVector = new float[20];
                for (int j = 0; j < 20; j++)
                {
                    randomVector[j] = (float)myRandom.NextDouble();
                }

                manyVectors.Add(randomVector);
            }

            Console.WriteLine("Done creating random vectors.");

            graph.BuildGraph(manyVectors, new Random(42), parameters);
        }
 ```

**Comment by jelmerk** [comment]
Trying to create an index with a mere 100.000 elements seems to cause an OutOffMemoryException 

```csharp
       /// <summary>
        /// See if we can create a large graph
        /// </summary>
        [TestMethod]
        public void LargeGraphTest()
        {
            var parameters = new SmallWorld<float[], float>.Parameters();
            parameters.M = 15;
            parameters.LevelLambda = 1 / Math.Log(parameters.M);

            var graph = new SmallWorld<float[], float>(CosineDistance.NonOptimized);

            var myRandom = new Random(42);

            var manyVectors = new List<float[]>();
            for (int i = 0; i < 100_000; i++)
            {
                var randomVector = new float[20];
                for (int j = 0; j < 20; j++)
                {
                    randomVector[j] = (float)myRandom.NextDouble();
                }

                manyVectors.Add(randomVector);
            }

            Console.WriteLine("Done creating random vectors.");

            graph.BuildGraph(manyVectors, new Random(42), parameters);
        }
 ```

**Comment by wlou** [comment]
Thanks for trying it out and for the report.
There is a big room for improvement in terms of memory consumption.

The `Node` structure is inefficient and is the main target for optimizations. As a quick workaround I can suggest to build x64 binaries and disable/clean cache in the `TravelingCosts`. The test is passed taking slightly less than 6Gb for me.

I'll take a closer look and address the issue properly meantime.

**Comment by jelmerk** [comment]
Thanks for taking a look. I had already worked out that removing the cache at least makes it not crash but the memory footprint is still huge and the index sizes I need it to work for are millions of vectors. This is where approximate nearest neighbour search is most appropriate.

Now it feels like it's a solution for solving problems you have with large datasets ... that does not support large datasets :-)

Do you have any plans to improve this library and make it more production ready ?

**Comment by wlou** [comment]
To be honest we never aimed to such a scale. Our use case was a low latency search (linear scan was too slow) among couple of thousands of high dimensional (>100) vectors. As of today I maintain this library on the "best effort basis". And we are welcome any contributions and improvements.

Regarding the issue, I think there are some low hanging fruits there and I'll try to make and publish a couple of optimizations during this and the next week.

But in general the algorithm should scale horizontally well by adding nodes.

**Comment by wlou** [comment]
Have a draft with optimizations.
@jelmerk, once the PR #7 is completed your test case (with disabled cache) should work in x86 environment.

**Comment by wlou** [comment]
PR #7 is completed. Now 1 million vectors scenario works taking about 372 Mb and 35 minutes.

**Comment by jelmerk** [comment]
great! i'll give this a try later today. thanks
